print('Obliczanie pola trapezu...')
a = int(input('Podaj dlugosc gornej podstawy: '))
b = int(input('Podaj dlugosc dolnej podstawy: '))
h = int(input('Podaj wysokosc: '))
print('Pole trapezu wynosi: ', (a+b)/2*h)